# Use the Docker-in-Docker service to build and push container images
image: docker:latest

services:
  - docker:dind

variables:
  # Enable Docker's BuildKit for faster, more flexible builds (optional):
  DOCKER_BUILDKIT: 1
  # Storage driver for Docker-in-Docker
  DOCKER_DRIVER: overlay2
  # Use Docker TLS certificates
  DOCKER_TLS_CERTDIR: /certs

stages:
  - build

build_docker_image:
  stage: build
  script:
    - echo "Logging in to GitLab container registry..."
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    # Build the Docker image using your Dockerfile
    # Adjust the build context (.) or path if your Dockerfile is in a subdirectory
    - docker build -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA" .
    # (Optionally) Tag the image with something like 'latest' as well
    - docker tag "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA" "$CI_REGISTRY_IMAGE:latest"
    # Push the image to the GitLab Container Registry
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA"
    - docker push "$CI_REGISTRY_IMAGE:latest"

  # Example: run this only on the main branch or when a tag is pushed
  only:
    - main
    - tags
